APP_NAME = 'lockdown'
APP_VERSION = 0.1

TEXT_GAME_TITLE = 'LOCKDOWN'
TEXT_START = 'Start'
TEXT_GAMEOVER = 'Game Over'
TEXT_SCORE = 'SCORE : '
TEXT_HIGH_SCORE = 'HIGH SCORE : '

WINDOW_SIZE = (800,600)
